defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    uid: 697da4c2-e02f-4f49-9d76-e22609ceda25 # Pages
handle: pages
maxAuthors: 1
name: Pages
previewTargets:
  -
    label: 'Primary entry page'
    refresh: '1'
    urlFormat: '{uri}'
propagationMethod: all
siteSettings:
  58ccb571-6c72-449f-8e7b-6f43c5d416b3: # Dreams
    enabledByDefault: true
    hasUrls: true
    template: null
    uriFormat: '{parent.uri ?? null}/{slug}'
structure:
  maxLevels: null
  uid: 97fc32ea-6e86-45dd-b3dd-97cdc4360518
type: structure
